name: Panoptic
version: 1.3.2
main: eu.mikart.panoptic.PanopticPlugin
loader: eu.mikart.panoptic.PanopticLoader
api-version: '1.21.1'
dependencies:
  server:
    MiniPlaceholders:
      load: AFTER
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
