name: Panoptic
version: 1.2.0
main: eu.mikart.panoptic.PanopticPlugin
api-version: '1.21.1'
dependencies:
  server:
    MiniPlaceholders:
      load: AFTER
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true